name: Dotnet API Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-dotnet:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        dotnet-version:
          - "8.x"
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: make install

      - name: Build
        run: make build

      - name: Test unit tests
        run: make test-unit
